### ISSUE TITLE
Implement undead/zombie feeds?

### ISSUE THREAD

**Issue by philbudne** [mediacloud/backup-rss-fetcher#38]
@NullPxl suggested that instead of auto-disabling feeds, we instead poll them very slowly.

One concern is how to signal this status to users looking at the web search "catalog" of sources & feeds.

The crudest way to do this would be to continue to set `system_enabled` to false, but to only use it to control the upper limit of poll interval (that is, select an alternate `MAXIMUM_BACKOFF_MINS` value, perhaps `MAXIMUM_ZOMBIE_BACKOFF_DAYS`?).  The UI could just display zombie or poop emoji instead of a red X.

However, `system_enabled` is used in the staging database to limit the number of feeds that are actually polled.  Adding a `system_undead` column boolean column, or making `system_enabled` a tristate would allow explicit disabling of feeds.

**Comment by NullPxl** [comment]
I like the tristate idea, is this how you would imagine system_enabled working?
0 (❌) - Explicitly set to disable the feed. Used in staging database to limit polls as you mentioned.
1 (✅) - The feed is working (or has not yet hit the failure threshold).
2 (💀/💩/🧟) - Feed failure threshold hit (such as the current points system); polling is significantly reduced.

Adding a little tooltip on hover for the zombie/skull feeds to say something like `Unable to reach feed - polling has been reduced` might be helpful. (or a legend somewhere)

**Comment by philbudne** [comment]
Implemented in https://github.com/mediacloud/rss-fetcher/commit/364a91d9809df0655c3bc355f71f723de8e1b8db

## v0.16.8 2024-09-08

* fetcher/config.py: remove `REDIS_URL`, add `UNDEAD_FEED{S,_MAX_DAYS`}
* fetcher/tasks.py: if `UNDEAD_FEEDS` set:
	1. never disable feeds
	2. use `UNDEAD_FEED_MAX_DAYS` instead of `MAXIMUM_BACKOFF_MINS`
	   (if failures > `MAX_FAILURES`)

`UNDEAD_FEEDS` defaults to `True`, `UNDEAD_FEED_MAX_DAYS` to `30`
