### ISSUE TITLE
Turn off sync of generated RSS files to AWS S3

### ISSUE THREAD

**Issue by philbudne** [mediacloud/backup-rss-fetcher#43]
Once IA confirms they're pulling generated RSS files from B2, and all indexer usage changed, disable sync to S3

**Comment by pgulley** [comment]
IA has confirmed that they've successfully pulled today's data from B2- so I think this is ready

**Comment by philbudne** [comment]
Depends on https://github.com/mediacloud/story-indexer/issues/326

**Comment by philbudne** [comment]
Done.
